// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: protoStruct/messages.proto

package protoStruct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------- Общий запрос от клиента
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_protoStruct_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ------------------------------------------- Общий ответ от сервера
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_protoStruct_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ------------------------------------------- Структуры транзакций
type ReqTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqTransaction) Reset() {
	*x = ReqTransaction{}
	mi := &file_protoStruct_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqTransaction) ProtoMessage() {}

func (x *ReqTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqTransaction.ProtoReflect.Descriptor instead.
func (*ReqTransaction) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ReqTransaction) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type RespTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Direction     string                 `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespTransaction) Reset() {
	*x = RespTransaction{}
	mi := &file_protoStruct_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespTransaction) ProtoMessage() {}

func (x *RespTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespTransaction.ProtoReflect.Descriptor instead.
func (*RespTransaction) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RespTransaction) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *RespTransaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *RespTransaction) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RespTransaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RespTransaction) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *RespTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RespTransaction) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RespTransaction) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ReqTransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqTransactionList) Reset() {
	*x = ReqTransactionList{}
	mi := &file_protoStruct_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqTransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqTransactionList) ProtoMessage() {}

func (x *ReqTransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqTransactionList.ProtoReflect.Descriptor instead.
func (*ReqTransactionList) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{4}
}

type RespTransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*RespTransaction     `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespTransactionList) Reset() {
	*x = RespTransactionList{}
	mi := &file_protoStruct_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespTransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespTransactionList) ProtoMessage() {}

func (x *RespTransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespTransactionList.ProtoReflect.Descriptor instead.
func (*RespTransactionList) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{5}
}

func (x *RespTransactionList) GetTransactions() []*RespTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// ------------------------------------------- Структуры сомнительных транзакций
type ReqDoubtfulTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  int64                  `protobuf:"varint,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqDoubtfulTransaction) Reset() {
	*x = ReqDoubtfulTransaction{}
	mi := &file_protoStruct_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqDoubtfulTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDoubtfulTransaction) ProtoMessage() {}

func (x *ReqDoubtfulTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDoubtfulTransaction.ProtoReflect.Descriptor instead.
func (*ReqDoubtfulTransaction) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ReqDoubtfulTransaction) GetAssessmentId() int64 {
	if x != nil {
		return x.AssessmentId
	}
	return 0
}

type RespDoubtfulTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	RiskScore     int64                  `protobuf:"varint,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Decision      string                 `protobuf:"bytes,4,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespDoubtfulTransaction) Reset() {
	*x = RespDoubtfulTransaction{}
	mi := &file_protoStruct_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespDoubtfulTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespDoubtfulTransaction) ProtoMessage() {}

func (x *RespDoubtfulTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespDoubtfulTransaction.ProtoReflect.Descriptor instead.
func (*RespDoubtfulTransaction) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{7}
}

func (x *RespDoubtfulTransaction) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *RespDoubtfulTransaction) GetRiskScore() int64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *RespDoubtfulTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RespDoubtfulTransaction) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

type ReqDoubtfulTransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqDoubtfulTransactionList) Reset() {
	*x = ReqDoubtfulTransactionList{}
	mi := &file_protoStruct_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqDoubtfulTransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDoubtfulTransactionList) ProtoMessage() {}

func (x *ReqDoubtfulTransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDoubtfulTransactionList.ProtoReflect.Descriptor instead.
func (*ReqDoubtfulTransactionList) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{8}
}

type RespDoubtfulTransactionList struct {
	state                protoimpl.MessageState     `protogen:"open.v1"`
	DoubtfulTransactions []*RespDoubtfulTransaction `protobuf:"bytes,1,rep,name=doubtful_transactions,json=doubtfulTransactions,proto3" json:"doubtful_transactions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RespDoubtfulTransactionList) Reset() {
	*x = RespDoubtfulTransactionList{}
	mi := &file_protoStruct_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespDoubtfulTransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespDoubtfulTransactionList) ProtoMessage() {}

func (x *RespDoubtfulTransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespDoubtfulTransactionList.ProtoReflect.Descriptor instead.
func (*RespDoubtfulTransactionList) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{9}
}

func (x *RespDoubtfulTransactionList) GetDoubtfulTransactions() []*RespDoubtfulTransaction {
	if x != nil {
		return x.DoubtfulTransactions
	}
	return nil
}

type ReqChangeDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Decision      string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqChangeDecision) Reset() {
	*x = ReqChangeDecision{}
	mi := &file_protoStruct_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqChangeDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChangeDecision) ProtoMessage() {}

func (x *ReqChangeDecision) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChangeDecision.ProtoReflect.Descriptor instead.
func (*ReqChangeDecision) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ReqChangeDecision) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *ReqChangeDecision) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

type RespChangeDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespChangeDecision) Reset() {
	*x = RespChangeDecision{}
	mi := &file_protoStruct_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespChangeDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespChangeDecision) ProtoMessage() {}

func (x *RespChangeDecision) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespChangeDecision.ProtoReflect.Descriptor instead.
func (*RespChangeDecision) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{11}
}

// ------------------------------------------- Структуры пользователей
type ReqRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqRegistration) Reset() {
	*x = ReqRegistration{}
	mi := &file_protoStruct_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRegistration) ProtoMessage() {}

func (x *ReqRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRegistration.ProtoReflect.Descriptor instead.
func (*ReqRegistration) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ReqRegistration) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ReqRegistration) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RespRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespRegistration) Reset() {
	*x = RespRegistration{}
	mi := &file_protoStruct_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespRegistration) ProtoMessage() {}

func (x *RespRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespRegistration.ProtoReflect.Descriptor instead.
func (*RespRegistration) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{13}
}

type ReqAuthentication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqAuthentication) Reset() {
	*x = ReqAuthentication{}
	mi := &file_protoStruct_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAuthentication) ProtoMessage() {}

func (x *ReqAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAuthentication.ProtoReflect.Descriptor instead.
func (*ReqAuthentication) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ReqAuthentication) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ReqAuthentication) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RespAuthentication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewToken      string                 `protobuf:"bytes,1,opt,name=newToken,proto3" json:"newToken,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespAuthentication) Reset() {
	*x = RespAuthentication{}
	mi := &file_protoStruct_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespAuthentication) ProtoMessage() {}

func (x *RespAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespAuthentication.ProtoReflect.Descriptor instead.
func (*RespAuthentication) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{15}
}

func (x *RespAuthentication) GetNewToken() string {
	if x != nil {
		return x.NewToken
	}
	return ""
}

func (x *RespAuthentication) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type ReqUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUser) Reset() {
	*x = ReqUser{}
	mi := &file_protoStruct_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUser) ProtoMessage() {}

func (x *ReqUser) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUser.ProtoReflect.Descriptor instead.
func (*ReqUser) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{16}
}

func (x *ReqUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RespUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	RoleId        int64                  `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespUser) Reset() {
	*x = RespUser{}
	mi := &file_protoStruct_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespUser) ProtoMessage() {}

func (x *RespUser) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespUser.ProtoReflect.Descriptor instead.
func (*RespUser) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{17}
}

func (x *RespUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RespUser) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RespUser) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RespUser) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type RespUserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*RespUser            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespUserList) Reset() {
	*x = RespUserList{}
	mi := &file_protoStruct_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespUserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespUserList) ProtoMessage() {}

func (x *RespUserList) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespUserList.ProtoReflect.Descriptor instead.
func (*RespUserList) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{18}
}

func (x *RespUserList) GetUsers() []*RespUser {
	if x != nil {
		return x.Users
	}
	return nil
}

// ------------------------------------------- Структуры фрод-правил
type ReqFraudRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int64                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqFraudRule) Reset() {
	*x = ReqFraudRule{}
	mi := &file_protoStruct_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqFraudRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqFraudRule) ProtoMessage() {}

func (x *ReqFraudRule) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqFraudRule.ProtoReflect.Descriptor instead.
func (*ReqFraudRule) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{19}
}

func (x *ReqFraudRule) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

type RespFraudRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int64                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	FieldName     string                 `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	Operator      string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Value         string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	AddRisk       int64                  `protobuf:"varint,7,opt,name=add_risk,json=addRisk,proto3" json:"add_risk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespFraudRule) Reset() {
	*x = RespFraudRule{}
	mi := &file_protoStruct_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespFraudRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespFraudRule) ProtoMessage() {}

func (x *RespFraudRule) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespFraudRule.ProtoReflect.Descriptor instead.
func (*RespFraudRule) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{20}
}

func (x *RespFraudRule) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *RespFraudRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RespFraudRule) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *RespFraudRule) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *RespFraudRule) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *RespFraudRule) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RespFraudRule) GetAddRisk() int64 {
	if x != nil {
		return x.AddRisk
	}
	return 0
}

type ReqFraudRuleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqFraudRuleList) Reset() {
	*x = ReqFraudRuleList{}
	mi := &file_protoStruct_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqFraudRuleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqFraudRuleList) ProtoMessage() {}

func (x *ReqFraudRuleList) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqFraudRuleList.ProtoReflect.Descriptor instead.
func (*ReqFraudRuleList) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{21}
}

type RespFraudRuleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FraudRules    []*RespFraudRule       `protobuf:"bytes,1,rep,name=fraud_rules,json=fraudRules,proto3" json:"fraud_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespFraudRuleList) Reset() {
	*x = RespFraudRuleList{}
	mi := &file_protoStruct_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespFraudRuleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespFraudRuleList) ProtoMessage() {}

func (x *RespFraudRuleList) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespFraudRuleList.ProtoReflect.Descriptor instead.
func (*RespFraudRuleList) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{22}
}

func (x *RespFraudRuleList) GetFraudRules() []*RespFraudRule {
	if x != nil {
		return x.FraudRules
	}
	return nil
}

type ReqChangeFraudRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int64                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	FieldName     string                 `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	Operator      string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Value         string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	AddRisk       int64                  `protobuf:"varint,7,opt,name=add_risk,json=addRisk,proto3" json:"add_risk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqChangeFraudRule) Reset() {
	*x = ReqChangeFraudRule{}
	mi := &file_protoStruct_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqChangeFraudRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChangeFraudRule) ProtoMessage() {}

func (x *ReqChangeFraudRule) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChangeFraudRule.ProtoReflect.Descriptor instead.
func (*ReqChangeFraudRule) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{23}
}

func (x *ReqChangeFraudRule) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *ReqChangeFraudRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqChangeFraudRule) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ReqChangeFraudRule) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *ReqChangeFraudRule) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ReqChangeFraudRule) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ReqChangeFraudRule) GetAddRisk() int64 {
	if x != nil {
		return x.AddRisk
	}
	return 0
}

type RespChangeFraudRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespChangeFraudRule) Reset() {
	*x = RespChangeFraudRule{}
	mi := &file_protoStruct_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespChangeFraudRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespChangeFraudRule) ProtoMessage() {}

func (x *RespChangeFraudRule) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespChangeFraudRule.ProtoReflect.Descriptor instead.
func (*RespChangeFraudRule) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{24}
}

var File_protoStruct_messages_proto protoreflect.FileDescriptor

const file_protoStruct_messages_proto_rawDesc = "" +
	"\n" +
	"\x1aprotoStruct/messages.proto\x12\bmessages\"M\n" +
	"\aRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"H\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"7\n" +
	"\x0eReqTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\"\xf0\x01\n" +
	"\x0fRespTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\tR\tdirection\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\x14\n" +
	"\x12ReqTransactionList\"T\n" +
	"\x13RespTransactionList\x12=\n" +
	"\ftransactions\x18\x01 \x03(\v2\x19.messages.RespTransactionR\ftransactions\"=\n" +
	"\x16ReqDoubtfulTransaction\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\x03R\fassessmentId\"\x9d\x01\n" +
	"\x17RespDoubtfulTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x03R\triskScore\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bdecision\x18\x04 \x01(\tR\bdecision\"\x1c\n" +
	"\x1aReqDoubtfulTransactionList\"u\n" +
	"\x1bRespDoubtfulTransactionList\x12V\n" +
	"\x15doubtful_transactions\x18\x01 \x03(\v2!.messages.RespDoubtfulTransactionR\x14doubtfulTransactions\"V\n" +
	"\x11ReqChangeDecision\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\"\x14\n" +
	"\x12RespChangeDecision\"C\n" +
	"\x0fReqRegistration\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x12\n" +
	"\x10RespRegistration\"E\n" +
	"\x11ReqAuthentication\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"I\n" +
	"\x12RespAuthentication\x12\x1a\n" +
	"\bnewToken\x18\x01 \x01(\tR\bnewToken\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\"\"\n" +
	"\aReqUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"q\n" +
	"\bRespUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\x03R\x06roleId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"8\n" +
	"\fRespUserList\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.messages.RespUserR\x05users\"'\n" +
	"\fReqFraudRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x03R\x06ruleId\"\xc0\x01\n" +
	"\rRespFraudRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x03R\x06ruleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"field_name\x18\x04 \x01(\tR\tfieldName\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x06 \x01(\tR\x05value\x12\x19\n" +
	"\badd_risk\x18\a \x01(\x03R\aaddRisk\"\x12\n" +
	"\x10ReqFraudRuleList\"M\n" +
	"\x11RespFraudRuleList\x128\n" +
	"\vfraud_rules\x18\x01 \x03(\v2\x17.messages.RespFraudRuleR\n" +
	"fraudRules\"\xc5\x01\n" +
	"\x12ReqChangeFraudRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x03R\x06ruleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"field_name\x18\x04 \x01(\tR\tfieldName\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x06 \x01(\tR\x05value\x12\x19\n" +
	"\badd_risk\x18\a \x01(\x03R\aaddRisk\"\x15\n" +
	"\x13RespChangeFraudRuleB\x0fZ\r./protoStructb\x06proto3"

var (
	file_protoStruct_messages_proto_rawDescOnce sync.Once
	file_protoStruct_messages_proto_rawDescData []byte
)

func file_protoStruct_messages_proto_rawDescGZIP() []byte {
	file_protoStruct_messages_proto_rawDescOnce.Do(func() {
		file_protoStruct_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoStruct_messages_proto_rawDesc), len(file_protoStruct_messages_proto_rawDesc)))
	})
	return file_protoStruct_messages_proto_rawDescData
}

var file_protoStruct_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_protoStruct_messages_proto_goTypes = []any{
	(*Request)(nil),                     // 0: messages.Request
	(*Response)(nil),                    // 1: messages.Response
	(*ReqTransaction)(nil),              // 2: messages.ReqTransaction
	(*RespTransaction)(nil),             // 3: messages.RespTransaction
	(*ReqTransactionList)(nil),          // 4: messages.ReqTransactionList
	(*RespTransactionList)(nil),         // 5: messages.RespTransactionList
	(*ReqDoubtfulTransaction)(nil),      // 6: messages.ReqDoubtfulTransaction
	(*RespDoubtfulTransaction)(nil),     // 7: messages.RespDoubtfulTransaction
	(*ReqDoubtfulTransactionList)(nil),  // 8: messages.ReqDoubtfulTransactionList
	(*RespDoubtfulTransactionList)(nil), // 9: messages.RespDoubtfulTransactionList
	(*ReqChangeDecision)(nil),           // 10: messages.ReqChangeDecision
	(*RespChangeDecision)(nil),          // 11: messages.RespChangeDecision
	(*ReqRegistration)(nil),             // 12: messages.ReqRegistration
	(*RespRegistration)(nil),            // 13: messages.RespRegistration
	(*ReqAuthentication)(nil),           // 14: messages.ReqAuthentication
	(*RespAuthentication)(nil),          // 15: messages.RespAuthentication
	(*ReqUser)(nil),                     // 16: messages.ReqUser
	(*RespUser)(nil),                    // 17: messages.RespUser
	(*RespUserList)(nil),                // 18: messages.RespUserList
	(*ReqFraudRule)(nil),                // 19: messages.ReqFraudRule
	(*RespFraudRule)(nil),               // 20: messages.RespFraudRule
	(*ReqFraudRuleList)(nil),            // 21: messages.ReqFraudRuleList
	(*RespFraudRuleList)(nil),           // 22: messages.RespFraudRuleList
	(*ReqChangeFraudRule)(nil),          // 23: messages.ReqChangeFraudRule
	(*RespChangeFraudRule)(nil),         // 24: messages.RespChangeFraudRule
}
var file_protoStruct_messages_proto_depIdxs = []int32{
	3,  // 0: messages.RespTransactionList.transactions:type_name -> messages.RespTransaction
	7,  // 1: messages.RespDoubtfulTransactionList.doubtful_transactions:type_name -> messages.RespDoubtfulTransaction
	17, // 2: messages.RespUserList.users:type_name -> messages.RespUser
	20, // 3: messages.RespFraudRuleList.fraud_rules:type_name -> messages.RespFraudRule
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protoStruct_messages_proto_init() }
func file_protoStruct_messages_proto_init() {
	if File_protoStruct_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoStruct_messages_proto_rawDesc), len(file_protoStruct_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoStruct_messages_proto_goTypes,
		DependencyIndexes: file_protoStruct_messages_proto_depIdxs,
		MessageInfos:      file_protoStruct_messages_proto_msgTypes,
	}.Build()
	File_protoStruct_messages_proto = out.File
	file_protoStruct_messages_proto_goTypes = nil
	file_protoStruct_messages_proto_depIdxs = nil
}
