// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: protoStruct/messages.proto

package protoStruct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Общий запрос от клиента
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // "ping", "get_user", "auth", "subscribe" и т.д.
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // сериализованные данные конкретного типа (Any или конкретное сообщение)
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`     // JWT или другой токен
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_protoStruct_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Общий ответ от сервера
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_protoStruct_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Структуры транзакций
type ReqTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqTransaction) Reset() {
	*x = ReqTransaction{}
	mi := &file_protoStruct_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqTransaction) ProtoMessage() {}

func (x *ReqTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqTransaction.ProtoReflect.Descriptor instead.
func (*ReqTransaction) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ReqTransaction) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type RespTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespTransaction) Reset() {
	*x = RespTransaction{}
	mi := &file_protoStruct_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespTransaction) ProtoMessage() {}

func (x *RespTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespTransaction.ProtoReflect.Descriptor instead.
func (*RespTransaction) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RespTransaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *RespTransaction) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RespTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RespTransaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RespTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RespTransaction) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RespTransaction) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ReqTransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqTransactionList) Reset() {
	*x = ReqTransactionList{}
	mi := &file_protoStruct_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqTransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqTransactionList) ProtoMessage() {}

func (x *ReqTransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqTransactionList.ProtoReflect.Descriptor instead.
func (*ReqTransactionList) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{4}
}

type RespTransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*RespTransaction     `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespTransactionList) Reset() {
	*x = RespTransactionList{}
	mi := &file_protoStruct_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespTransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespTransactionList) ProtoMessage() {}

func (x *RespTransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespTransactionList.ProtoReflect.Descriptor instead.
func (*RespTransactionList) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{5}
}

func (x *RespTransactionList) GetTransactions() []*RespTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// Структуры пользователей
type ReqRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqRegistration) Reset() {
	*x = ReqRegistration{}
	mi := &file_protoStruct_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRegistration) ProtoMessage() {}

func (x *ReqRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRegistration.ProtoReflect.Descriptor instead.
func (*ReqRegistration) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ReqRegistration) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ReqRegistration) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RespRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespRegistration) Reset() {
	*x = RespRegistration{}
	mi := &file_protoStruct_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespRegistration) ProtoMessage() {}

func (x *RespRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespRegistration.ProtoReflect.Descriptor instead.
func (*RespRegistration) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{7}
}

func (x *RespRegistration) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ReqAuthentication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqAuthentication) Reset() {
	*x = ReqAuthentication{}
	mi := &file_protoStruct_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAuthentication) ProtoMessage() {}

func (x *ReqAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAuthentication.ProtoReflect.Descriptor instead.
func (*ReqAuthentication) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ReqAuthentication) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ReqAuthentication) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RespAuthentication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewToken      string                 `protobuf:"bytes,1,opt,name=newToken,proto3" json:"newToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespAuthentication) Reset() {
	*x = RespAuthentication{}
	mi := &file_protoStruct_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespAuthentication) ProtoMessage() {}

func (x *RespAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_protoStruct_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespAuthentication.ProtoReflect.Descriptor instead.
func (*RespAuthentication) Descriptor() ([]byte, []int) {
	return file_protoStruct_messages_proto_rawDescGZIP(), []int{9}
}

func (x *RespAuthentication) GetNewToken() string {
	if x != nil {
		return x.NewToken
	}
	return ""
}

var File_protoStruct_messages_proto protoreflect.FileDescriptor

const file_protoStruct_messages_proto_rawDesc = "" +
	"\n" +
	"\x1aprotoStruct/messages.proto\x12\bmessages\"M\n" +
	"\aRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"H\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"7\n" +
	"\x0eReqTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\"\xc9\x01\n" +
	"\x0fRespTransaction\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\x14\n" +
	"\x12ReqTransactionList\"T\n" +
	"\x13RespTransactionList\x12=\n" +
	"\ftransactions\x18\x01 \x03(\v2\x19.messages.RespTransactionR\ftransactions\"C\n" +
	"\x0fReqRegistration\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\x10RespRegistration\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"E\n" +
	"\x11ReqAuthentication\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"0\n" +
	"\x12RespAuthentication\x12\x1a\n" +
	"\bnewToken\x18\x01 \x01(\tR\bnewTokenB\x0fZ\r./protoStructb\x06proto3"

var (
	file_protoStruct_messages_proto_rawDescOnce sync.Once
	file_protoStruct_messages_proto_rawDescData []byte
)

func file_protoStruct_messages_proto_rawDescGZIP() []byte {
	file_protoStruct_messages_proto_rawDescOnce.Do(func() {
		file_protoStruct_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoStruct_messages_proto_rawDesc), len(file_protoStruct_messages_proto_rawDesc)))
	})
	return file_protoStruct_messages_proto_rawDescData
}

var file_protoStruct_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protoStruct_messages_proto_goTypes = []any{
	(*Request)(nil),             // 0: messages.Request
	(*Response)(nil),            // 1: messages.Response
	(*ReqTransaction)(nil),      // 2: messages.ReqTransaction
	(*RespTransaction)(nil),     // 3: messages.RespTransaction
	(*ReqTransactionList)(nil),  // 4: messages.ReqTransactionList
	(*RespTransactionList)(nil), // 5: messages.RespTransactionList
	(*ReqRegistration)(nil),     // 6: messages.ReqRegistration
	(*RespRegistration)(nil),    // 7: messages.RespRegistration
	(*ReqAuthentication)(nil),   // 8: messages.ReqAuthentication
	(*RespAuthentication)(nil),  // 9: messages.RespAuthentication
}
var file_protoStruct_messages_proto_depIdxs = []int32{
	3, // 0: messages.RespTransactionList.transactions:type_name -> messages.RespTransaction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protoStruct_messages_proto_init() }
func file_protoStruct_messages_proto_init() {
	if File_protoStruct_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoStruct_messages_proto_rawDesc), len(file_protoStruct_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoStruct_messages_proto_goTypes,
		DependencyIndexes: file_protoStruct_messages_proto_depIdxs,
		MessageInfos:      file_protoStruct_messages_proto_msgTypes,
	}.Build()
	File_protoStruct_messages_proto = out.File
	file_protoStruct_messages_proto_goTypes = nil
	file_protoStruct_messages_proto_depIdxs = nil
}
