// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: protobuf/messages.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewToken      string                 `protobuf:"bytes,1,opt,name=newToken,proto3" json:"newToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationRequest) Reset() {
	*x = AuthenticationRequest{}
	mi := &file_protobuf_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationRequest) ProtoMessage() {}

func (x *AuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticationRequest) GetNewToken() string {
	if x != nil {
		return x.NewToken
	}
	return ""
}

type AuthenticationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationResponse) Reset() {
	*x = AuthenticationResponse{}
	mi := &file_protobuf_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationResponse) ProtoMessage() {}

func (x *AuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{1}
}

// Общий запрос от клиента
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // "ping", "get_user", "auth", "subscribe" и т.д.
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // сериализованные данные конкретного типа (Any или конкретное сообщение)
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`     // JWT или другой токен
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_protobuf_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Общий ответ от сервера
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // Any или конкретный тип
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_protobuf_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Кастомные структуры
type ReqTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqTransaction) Reset() {
	*x = ReqTransaction{}
	mi := &file_protobuf_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqTransaction) ProtoMessage() {}

func (x *ReqTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqTransaction.ProtoReflect.Descriptor instead.
func (*ReqTransaction) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ReqTransaction) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type RespTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespTransaction) Reset() {
	*x = RespTransaction{}
	mi := &file_protobuf_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespTransaction) ProtoMessage() {}

func (x *RespTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespTransaction.ProtoReflect.Descriptor instead.
func (*RespTransaction) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{5}
}

func (x *RespTransaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *RespTransaction) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RespTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RespTransaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RespTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RespTransaction) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RespTransaction) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ReqTransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*ReqTransaction      `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqTransactionList) Reset() {
	*x = ReqTransactionList{}
	mi := &file_protobuf_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqTransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqTransactionList) ProtoMessage() {}

func (x *ReqTransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqTransactionList.ProtoReflect.Descriptor instead.
func (*ReqTransactionList) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ReqTransactionList) GetTransactions() []*ReqTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type RespTransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespTransactionList) Reset() {
	*x = RespTransactionList{}
	mi := &file_protobuf_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespTransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespTransactionList) ProtoMessage() {}

func (x *RespTransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespTransactionList.ProtoReflect.Descriptor instead.
func (*RespTransactionList) Descriptor() ([]byte, []int) {
	return file_protobuf_messages_proto_rawDescGZIP(), []int{7}
}

var File_protobuf_messages_proto protoreflect.FileDescriptor

const file_protobuf_messages_proto_rawDesc = "" +
	"\n" +
	"\x17protobuf/messages.proto\x12\bmessages\"3\n" +
	"\x15AuthenticationRequest\x12\x1a\n" +
	"\bnewToken\x18\x01 \x01(\tR\bnewToken\"\x18\n" +
	"\x16AuthenticationResponse\"M\n" +
	"\aRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"H\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"7\n" +
	"\x0eReqTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\"\xc9\x01\n" +
	"\x0fRespTransaction\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"R\n" +
	"\x12ReqTransactionList\x12<\n" +
	"\ftransactions\x18\x01 \x03(\v2\x18.messages.ReqTransactionR\ftransactions\"\x15\n" +
	"\x13RespTransactionListB\fZ\n" +
	"./protobufb\x06proto3"

var (
	file_protobuf_messages_proto_rawDescOnce sync.Once
	file_protobuf_messages_proto_rawDescData []byte
)

func file_protobuf_messages_proto_rawDescGZIP() []byte {
	file_protobuf_messages_proto_rawDescOnce.Do(func() {
		file_protobuf_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_messages_proto_rawDesc), len(file_protobuf_messages_proto_rawDesc)))
	})
	return file_protobuf_messages_proto_rawDescData
}

var file_protobuf_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protobuf_messages_proto_goTypes = []any{
	(*AuthenticationRequest)(nil),  // 0: messages.AuthenticationRequest
	(*AuthenticationResponse)(nil), // 1: messages.AuthenticationResponse
	(*Request)(nil),                // 2: messages.Request
	(*Response)(nil),               // 3: messages.Response
	(*ReqTransaction)(nil),         // 4: messages.ReqTransaction
	(*RespTransaction)(nil),        // 5: messages.RespTransaction
	(*ReqTransactionList)(nil),     // 6: messages.ReqTransactionList
	(*RespTransactionList)(nil),    // 7: messages.RespTransactionList
}
var file_protobuf_messages_proto_depIdxs = []int32{
	4, // 0: messages.ReqTransactionList.transactions:type_name -> messages.ReqTransaction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_messages_proto_init() }
func file_protobuf_messages_proto_init() {
	if File_protobuf_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_messages_proto_rawDesc), len(file_protobuf_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_messages_proto_goTypes,
		DependencyIndexes: file_protobuf_messages_proto_depIdxs,
		MessageInfos:      file_protobuf_messages_proto_msgTypes,
	}.Build()
	File_protobuf_messages_proto = out.File
	file_protobuf_messages_proto_goTypes = nil
	file_protobuf_messages_proto_depIdxs = nil
}
