jwt: 
  secret: "very-good-secury"
  expiry-in: 1800s
postgres_db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "12345"
  db_name: "main-transactions"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s 
tcp_server:
    address: "localhost:8084"
    idle_timeout: 30s